---
- name: Install FreeIPA server
  hosts: ipas
  become: true
  tasks:
    - name: Include variables
      include_vars: vars.yml

    - name: Install required packages
      package:
        name: "{{ idm_rpms }}"
        state: installed

    - name: Upgrade NSS package
      package:
        name: nss
        state: latest

    - name: Ensure firewalld is running
      service:
        name: firewalld
        state: started
        enabled: true

    - name: Open Firewall for IdM use
      firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
        immediate: true
      loop: "{{ firewalld_service_ports }}"

    - name: Setup hostname entry
      lineinfile:
        dest: /etc/hosts
        line: "{{ ansible_default_ipv4.address }} {{ idm_dns_name }}"
        state: present

    - name: Configure initial IdM setup
      command: >
        ipa-server-install -U
          --hostname="{{ idm_dns_name | default(ansible_fqdn) }}"
          --domain="{{ idm_domain }}"
          --realm="{{ idm_realm | upper }}"
          --ds-password="{{ idm_dm_password }}"
          --admin-password="{{ idm_admin_password }}"
          --no-host-dns
      ignore_errors: true
      notify: Ensure IdM is running at boot

    - name: Comment all lines
      replace:
        path:  /tmp/aap2/finallab_report.txt
        regexp: "(.*)"
        replace: '#  \1'
      notify: Ensure IdM is running at boot

    - name: Insert lines
      lineinfile:
        path: /tmp/aap2/finallab_report.txt
        regex: EOF
        line: |
          RewriteEngine on
          RewriteRule ^/$ /ipa/ui [L,NC,R=301]
          RewriteRule ^/ipa/ui/js/freeipa/plugins.js$    /ipa/wsgi/plugins.py [PT]  
        notify: Ensure IdM is running at boot

  handlers:
    - name: Ensure IdM is running at boot
      service:
        name: ipa
        state: restarted
        enabled: true

- name: Create users and groups
  hosts: ipas
  gather_facts: false
  tasks:
    - name: Create IPA users
      ipa_user:
        name: "{{ item.user }}"
        givenname: "{{ item.user }}"
        sn: "{{ item.user }}"
        password: "{{ item.password }}"
        state: present
        update_password: on_create
        ipa_host: "{{ groups.ipas.0 }}"
        ipa_user: "{{ idm_principal }}"
        ipa_pass: "{{ idm_dm_password }}"
      loop: "{{ idm_users }}"

    - name: Create IPA groups
      ipa_group:
        name: "{{ item.group }}"
        user:
          - "{{ item.user }}"
        state: present
        ipa_host: "{{ groups.ipas.0 }}"
        ipa_user: "{{ idm_principal }}"
        ipa_pass: "{{ idm_dm_password }}"
      loop: "{{ idm_users }}"