---
- name: Provision started
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - debug:
        msg: "Provisioning started"

- name: Include variables
  hosts: localhost
  connection: localhost
  gather_facts: false
  # roles:
  #   - role: manager.common.common_vars

- name: Import pre-provision playbook from environment
  vars:
    find_provisioner:
      - "{{ lab_mgr_dir }}/environments/{{ provisioner }}/{{ env_name }}/pre-provison.yml"
      - ./none.yml
  import_playbook: "{{ lookup('first_found', find_provisioner) }}"


- name: Provision stack
  hosts: localhost
  connection: localhost
  gather_facts: false
  roles:
    - role: manager.osp.osp_infra_provisioner

    - role: manager.osp.osp_inventory


- name: Wait for host to be available
  hosts: all:!controls:!bastions:!satellites
  gather_facts: false
  tasks:
    - when: "env_destroy | default(false) | bool != true"
      block:
        - name: wait for host to be available
          wait_for_connection:
            delay: 30
            timeout: 300
            connect_timeout: 10
          register: rwait
    
        - ping:
          register: rping
          retries: 3
          delay: 10
          until: rping is succeeded

- name: Reload Inventory
  hosts: localhost
  connection: local
  gather_facts: false 
  tasks:
    - meta: refresh_inventory

    - debug:
        msg: "Provisioning finished"