---

- name: Include variables
  hosts: localhost
  connection: localhost
  gather_facts: false
  roles:
    - role: manager.common.common_vars

- name: Import destroy playbook from environment
  vars:
    find_destroy:
      - "{{ lab_mgr_dir }}/environments/{{ provisioner }}/{{ env_name }}/destroy.yml"
      - ./none.yml
  import_playbook: "{{ lookup('first_found', find_destroy) }}"


- name: Destroy stack
  hosts: localhost
  connection: localhost
  gather_facts: false
  roles:
    - role: manager.osp.osp_infra_destroy
    
  # tasks:
  #   - name: Destroy heat stack
  #     include_tasks: ../tasks/lab-env-destroy.yml

  #   - name: Saving inventory in /etc/ansible/hosts
  #     include_tasks: ../tasks/lab-ansible-inventory.yml

    # - name: update pod dns records
    #   include_tasks: ../tasks/lab-dns-records.yml
 

# common_inventory