---

- name: Deleting pods
  hosts: localhost
  connection: localhost
  gather_facts: false
  become: true
  tasks:
    ## Pod systemd service disable and stop
    - name: dislable and stop pods
      service:
        name: "{{ env_name }}-pod"
        enabled: false
        state: stopped
      async: 3000
      poll: 30

    # Pod systemd service file
    - name: delete podman systemd service config
      file:
        path: "/usr/lib/systemd/system/{{ env_name }}-pod.service"
        state: absent

    ## Pod systemd service enable/start
    - name: Reload systemd daemon
      command: /usr/bin/systemctl daemon-reload

    # Pod orchestration directory
    - name: delete podman orchestration directory
      file:
        path: "/opt/podman/pods/{{ env_name }}-pod/"
        state: absent

    # Pod volume directory
    - name: delete podman volume directories
      file:
        path: "/opt/podman/volumes/{{ env_name }}-volume/"
        state: absent

