---
- hosts: localhost
  gather_facts: false
  vars:
    guid: "{{ lookup('env','GUID') }}"
    home: "{{ lookup('env','HOME') }}"
    internal_domain: "{{ lookup('env','INTERNAL_DOMAIN') }}"
  tasks:
### List Credentials #####
    - name: List Credentials
      uri:
        url: https://{{ ac.url }}/api/v2/credentials/
        user: "{{ ac.user }}"
        password: "{{ ac.password }}"
        method: GET
        force_basic_auth: yes
        validate_certs: false
        body_format: json
        status_code: 200
      register: r_credentials
      ignore_errors: true

##### Result for Container registry #####     
    - name: "Success - set fact"
      set_fact:
        success: true
      when: 
        - r_credentials.json.results is defined
        - infra.container_cred == item.name
      loop: "{{ r_credentials.json.results }}"

    - name: Import logging role
      import_role:
        name: manager.grade.logging_grade_to_log
      vars:
        task_description_message: "Checking (Infra) Container Registry Credentials [{{ infra.container_cred }}]"

##### Result for Cloud Credentials #####
    - name: "Success - set fact"
      set_fact:
        success: true
      when:
        - r_credentials.json.results is defined 
        - infra.cloud_cred == item.name
      loop: "{{ r_credentials.json.results }}"

    - name: Import logging role
      import_role:
        name: manager.grade.logging_grade_to_log
      vars:
        task_description_message: "Checking (Infra) Cloud Credentials [{{ infra.cloud_cred }}]"

##### Result for Machine Credential #####
    - name: "Success - set fact"
      set_fact:
        success: true
      when: 
        - r_credentials.json.results is defined
        - infra.machine_cred == item.name
      loop: "{{ r_credentials.json.results }}"

    - name: Import logging role
      import_role:
        name: manager.grade.logging_grade_to_log
      vars:
        task_description_message: "Checking (Infra) Machine Credential [{{ infra.machine_cred }}]"

#### List Execution Environment ####
    - name: List Job templates
      uri:
        url: https://{{ ac.url }}/api/v2/execution_environments/
        user: "{{ ac.user }}"
        password: "{{ ac.password }}"
        method: GET
        force_basic_auth: yes
        validate_certs: false
        body_format: json
        status_code: 200
      register: r_ee
      ignore_errors: true

##### Result for Execution Environment #####
    - name: "Success - set fact"
      set_fact:
        success: true
      when: 
        - r_ee.json.results is defined
        - infra.ee ==  item.name
      loop: "{{ r_ee.json.results }}"

    - name: Import logging role
      import_role:
        name: manager.grade.logging_grade_to_log
      vars:
        task_description_message: "Checking (Infra) Execution Environment [{{ infra.ee }}]"


#### List Projects ####
    - name: List Job templates
      uri:
        url: https://{{ ac.url }}/api/v2/projects/
        user: "{{ ac.user }}"
        password: "{{ ac.password }}"
        method: GET
        force_basic_auth: yes
        validate_certs: false
        body_format: json
        status_code: 200
      register: r_projects
      ignore_errors: true

##### Result for Infra Projects #####
    - name: "Success - set fact"
      set_fact:
        success: true
      when: 
        - r_projects.json.results is defined
        - infra.project ==  item.name
      loop: "{{ r_projects.json.results }}"

    - name: Import logging role
      import_role:
        name: manager.grade.logging_grade_to_log
      vars:
        task_description_message: "Checking (Infra) Project [{{ infra.project }}]"

#### List job templates ####
    - name: List Job templates
      uri:
        url: https://{{ ac.url }}/api/v2/job_templates/
        user: "{{ ac.user }}"
        password: "{{ ac.password }}"
        method: GET
        force_basic_auth: yes
        validate_certs: false
        body_format: json
        status_code: 200
      register: r_jobtemplates
      ignore_errors: true


##### Result for Infra Job template #####
    - name: "Success - set fact"
      set_fact:
        success: true
      when: 
        - r_jobtemplates.json.results is defined
        - infra.job_template ==  item.name
      loop: "{{ r_jobtemplates.json.results }}"

    - name: Import logging role
      import_role:
        name: manager.grade.logging_grade_to_log
      vars:
        task_description_message: "Checking (Infra) Job Template [{{ infra.job_template }}]"

#### In-memory inventory ####
    - meta: refresh_inventory

    - name: Collection instance info
      os_server_info:
        cloud: "{{ guid }}-project"
      register: instances

    - name: Build In-Memory inventory
      add_host:
        host: "{{ item.name }}"
        group:
          - "{{ item.metadata.AnsibleGroup }}"
          - osp_instances
        ansible_host: "{{ item.private_v4 }}"
        ansible_user: cloud-user
        ansible_ssh_private_key_file: "{{ infra.ssh_key }}"
      when: item.metadata.type | default('') == "osp_instances"
      loop: "{{ instances.openstack_servers }}"


- hosts: localhost
  gather_facts: false
  tasks:
    ##### For frontend #####
    - name: Block for frontend
      when: hostvars.frontend is defined
      block:
        - name: Check frontend
          wait_for: 
            host: "{{ hostvars.frontend.ansible_host }}"
            port: 22
          register: r_frontend

    - debug: var=r_frontend
    
    - name: "Success - set fact"
      set_fact:
        success: true
      when: 
        - not r_frontend.failed | default(true) | bool
 
    - name: Import logging role
      import_role:
        name: manager.grade.logging_grade_to_log
      vars:
        task_description_message: "Checking (Infra) Node Provisioning [frontend]"

    ##### For App1 #####
    - name: Block for APP1
      when: hostvars.app1 is defined
      block:
        - name: Check App1
          wait_for: 
            host: "{{ hostvars.app1.ansible_host }}"
            port: 22
          register: r_app1

    - debug: var=r_app1

    - name: "Success - set fact"
      set_fact:
        success: true
      when:
        - not r_app1.failed | default(true)  | bool

    - name: Import logging role
      import_role:
        name: manager.grade.logging_grade_to_log
      vars:
        task_description_message: "Checking (Infra) Node Provisioning [app1]"


    ##### For App2 #####
    - name: Block for App2
      when: hostvars.app2 is defined
      block:
        - name: Ping App2
          wait_for: 
            host: "{{ hostvars.app2.ansible_host }}"
            port: 22
          register: r_app2

    - debug: var=r_app2

    - name: "Success - set fact"
      set_fact:
        success: true
      when: 
        - not r_app2.skkipped | bool
        - not r_app2.failed | bool

    - name: Import logging role
      import_role:
        name: manager.grade.logging_grade_to_log
      vars:
        task_description_message: "Checking (Infra) Node Provisioning [app2]"

    #### For Appdb ######
    - name: Block for Appdb
      when: hostvars.app2 is defined
      block:
        - name: Check Appdb
          wait_for: 
            host: "{{ hostvars.appdb.ansible_host }}"
            port: 22
          register: r_appdb

    - debug: var=r_appdb

    - name: "Success - set fact"
      set_fact:
        success: true
      when: 
        - not r_appdb.skipped |bool
        - not r_appdb.failed | bool

    - name: Import logging role
      import_role:
        name: manager.grade.logging_grade_to_log
      vars:
        task_description_message: "Checking (Infra) Node Provisioning [appdb]"



# - hosts: frontend
#   gather_facts: false
#   tasks:
#     - block:
#         - ping:
#           register: r_ping_frontend
#       always:
#           ##### Result for frontend #####
#         - name: "Success - set fact"
#           set_fact:
#             success: true
#           when: 
#             - r_ping_frontend.ping is defined
#             - r_ping_frontend.ping == "pong"

#         - name: Import logging role
#           import_role:
#             name: manager.grade.logging_grade_to_log
#           vars:
#             task_description_message: "Checking (Infra) Node Pprovisioning [frontend]"

# - hosts: app1
#   gather_facts: false
#   tasks:
#     - block:
#         - ping:
#           register: r_ping_app1
#           ignore_errors: true
#       always:
#         ##### Result for  app1 #####
#         - name: "Success - set fact"
#           set_fact:
#             success: true
#           when:
#             - r_ping_app1.ping  is defined
#             - r_ping_app1.ping == "pong"

#         - name: Import logging role
#           import_role:
#             name: manager.grade.logging_grade_to_log
#           vars:
#             task_description_message: "Checking (Infra) Node Provisioning [app1]"

# - hosts: app2
#   gather_facts: false
#   tasks:
#     - block:
#         - ping:
#           register: r_ping_app2

#       always:
#         ##### Result for app2 #####
#         - name: "Success - set fact"
#           set_fact:
#             success: true
#           when: 
#             - r_ping_app2.ping is defined
#             - r_ping_app2.ping == "pong"

#         - name: Import logging role
#           import_role:
#             name: manager.grade.logging_grade_to_log
#           vars:
#             task_description_message: "Checking (Infra) Node Provisioning [app2]"

# - hosts: appdb
#   gather_facts: false
#   tasks:
#     - block:
#         - ping:
#           register: r_ping_appdb
#         ##### Result for appdb #####
#       always:
#         - name: "Success - set fact"
#           set_fact:
#             success: true
#           when: 
#             - r_ping_appdb.ping is defined
#             - r_ping_appdb.ping == "pong"

#         - name: Import logging role
#           import_role:
#             name: manager.grade.logging_grade_to_log
#           vars:
#             task_description_message: "Checking (Infra) Node Provisioning [appdb]"
