---
- name: Check application
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
##### Result for Infra Projects #####
    - name: "No Success - set fact"
      set_fact:
        success: false

    - name: "Success - set fact"
      set_fact:
        success: true
      when: application.project ==  item.name
      loop: "{{ r_projects.json.results }}"

    - name: Import logging role
      import_role:
        name: manager.grade.logging_grade_to_log
      vars:
        task_description_message: "Checking (App) Project"


#### List App Inventory ####
    - name: List Inventory
      uri:
        url: https://{{ ac.url }}/api/v2/inventories/
        user: "{{ ac.user }}"
        password: "{{ ac.password }}"
        method: GET
        force_basic_auth: yes
        validate_certs: false
        body_format: json
        status_code: 200
      register: r_inventories

##### Result for Infra Job template #####
    - name: "No Success - set fact"
      set_fact:
        success: false

    - name: "Success - set fact"
      set_fact:
        success: true
      when: application.inventory ==  item.name
      loop: "{{ r_inventories.json.results }}"

    - name: Import logging role
      import_role:
        name: manager.grade.logging_grade_to_log
      vars:
        task_description_message: "Checking (App) Inventory"

#### Checking Application deployment
    - name: Checking Application deployment
      uri:
        url: http://{{ hostvars.frontend.ansible_host  }}/?name=root
        method: GET
        return_content: yes
      register: r_app_uri
      ignore_errors: yes

    - debug: var=r_app_uri
      when:
        - '"root redhat /bin/bash /root" in r_app_uri.content'
        - r_app_uri.status == 200

##### Result for Application deployment #####
    - name: "Success - set fact"
      set_fact:
        success: true
      when:
        - '"root redhat /bin/bash /root" in r_app_uri.content'
        - r_app_uri.status == 200

    - name: "No Success - set fact"
      set_fact:
        success: false
      when:
        - '"root redhat /bin/bash /root" not in r_app_uri.content'
        - r_app_uri.status != 200

    - name: Import logging role
      import_role:
        name: manager.grade.logging_grade_to_log
      vars:
        task_description_message: "Checking (App) Application Deployment"