---
- name: Convert clouds.yaml to json
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  tasks:
    - name: Create clouds.json file
      set_fact:
        clouds_json: "{{ lookup('file', '/etc/openstack/clouds.yaml') | from_yaml | to_nice_json }}"

