---

- import_playbook: "./defaults/playbooks/instance-provisioner.yml"
  when: 
    - 'provisioner == "instances"'
    - not env_destroy | default(false) | bool 

- import_playbook: "./defaults/playbooks/instance-config.yml"
  when:
    - 'provisioner == "instances"'
    - instance_configure | default(true) | bool
    - not env_destroy | default(false) | bool  

- import_playbook: "./defaults/playbooks/instance-destroy.yml"
  when: 
    - 'provisioner == "instances"'
    - env_destroy | default(false) | bool


- name: Configure Haproxy
  hosts: localhost
  connection: localhost
  gather_facts: false
  tasks:
    - name: Clean in-memory inventory
      meta: refresh_inventory

    - name: Setup haproxy pod
      include_tasks: ./defaults/playbooks/pod-reconfig-haproxy.yml

