---

- name: Include variables
  hosts:
    - localhost
  connection: localhost
  gather_facts: false
  tasks:
    - name: Include variables
      include_tasks: configs/include_vars.yml

    - set_fact:
        guid: "{{ access_details.guid }}"
        email: "{{ access_details.email }}"
        subdomain: "{{ access_details.subdomain }}"
        

    - name: Provision lab environment
      when: "env_destroy | default(false) | bool != true"
      block:
        - name: Provision lab environment
          include_tasks: configs/lab-provision.yml
    
        - name: Build inventory and records
          include_tasks: configs/lab-inventory.yml

    - name: Destroy lab environment
      when: env_destroy | default(false) | bool
      block:
        
        - include_tasks: configs/lab-destroy.yml

        - name: Build inventory and records
          include_tasks: configs/lab-inventory.yml

        - name: Reset haproxy pod
          include_tasks: configs/setup-haproxy-pod.yml

- name: Configure hosts
  hosts: all:!controls:!bastions:!satellites:!nodes
  become: true
  tasks:
    - name: Include variables
      include_tasks: configs/include_vars.yml

    - set_fact:
        guid: "{{ access_details.guid }}"
        email: "{{ access_details.email }}"
 
    - name: Configure lab environment
      when: "env_destroy | default(false) | bool != true"
      block:
        - name: Configure lab environment
          include_tasks: configs/lab-configure.yml


- name: Install Tower for finallab
  hosts: localhost
  connection: localhost
  gather_facts: false
  tasks:
    - name: Install Tower for Final lab
      when: 
        - env_type == "finallab"
        - env_destroy | default(false) != true
      block:
        - name: Include variables
          include_tasks: configs/include_vars.yml
          
        - name: Install Ansible Tower
          include_tasks: configs/install-towerfl.yml

- name: Configure Haproxy
  hosts: localhost
  connection: localhost
  gather_facts: false
  tasks:
    - name: Clean in-memory inventory
      meta: refresh_inventory

    - name: Setup haproxy pod
      include_tasks: configs/setup-haproxy-pod.yml

