---

- import_playbook: "./playbooks/instance-provisioner.yml"
  when: "env_destroy | default(false) | bool != true"

- import_playbook: "./playbooks/instance-config.yml"
  when: 
    - instance_configure | bool
    - "env_destroy | default(false) | bool != true"

- import_playbook: "./playbooks/instance-destroy.yml"
  when: env_destroy | default(false) | bool

- name: Final Lab play
  hosts: localhost
  connection: localhost
  gather_facts: false
  tasks:
    - name: Prepare ffinallab nodes
      when:
        - 'env_type == "finallab"'
        - 'env_destroy | default(false) | bool != true'
      block:
        - name: Include variables
          include_tasks: configs/include_vars.yml
          
        - name: Install Ansible Tower
          include_tasks: configs/install-towerfl.yml

- name: Configure Haproxy
  hosts: localhost
  connection: localhost
  gather_facts: false
  tasks:
    - name: Clean in-memory inventory
      meta: refresh_inventory

    - name: Setup haproxy pod
      include_tasks: configs/setup-haproxy-pod.yml

