---

- name: Find env
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Env finder
      include_role:
        name: manager.common.env_finder


- name: Include variables
  hosts: localhost:all
  roles:
    - manager.common.common_vars


- name: Import instances deployer and destroyer
  import_playbook: "{{ collections_dir }}/manager/common/playbooks/instances.yml"
  when: 
    - 'env_name is defined'
    - 'provisioner == "instances"'


- name: Import pods deployer and destroyer
  import_playbook: "{{ collections_dir }}/manager/common/playbooks/pods.yml"
  when: 
    - 'env_name is defined'
    - 'provisioner == "pods"'

