---

- name: Set collection dir
  hosts: 
    - localhost
    - all
  tasks:
    - set_fact:
        collections_dir: "./collections/ansible_collections/"


- name: Check if env_name is exist in provisioner
  import_playbook: "{{ collections_dir }}/manager/common/playbooks/env-finder.yml"
    

- name: Include variables
  hosts: localhost:all
  roles:
    - manager.common.common_vars


- name: Import instances deployer and destroyer
  import_playbook: "{{ collections_dir }}/manager/common/playbooks/instances.yml"
  when: 
    - 'env_name is defined'
    - 'provisioner == "instances"'


- name: Import pods deployer and destroyer
  import_playbook: "{{ collections_dir }}/manager/common/playbooks/pods.yml"
  when: 
    - 'env_name is defined'
    - 'provisioner == "pods"'