---

- import_playbook: "./defaults/playbooks/instance-provisioner.yml"
  when: 
    - "'provisioner' == 'instances'"
    - "env_destroy | default(false) | bool != true"

- import_playbook: "./defaults/playbooks/instance-config.yml"
  when:
    - "'provisioner' == 'instances'"
    - instance_configure | default(true) | bool
    - "env_destroy | default(false) | bool != true"

- import_playbook: "./defaults/playbooks/instance-destroy.yml"
  when: 
    - "'provisioner' == 'instances'"
    - env_destroy | default(false) | bool




- name: Final Lab play
  hosts: localhost
  connection: localhost
  gather_facts: false
  tasks:
    - name: Prepare ffinallab nodes
      when:
        - 'env_type == "finallab"'
        - 'env_destroy | default(false) | bool != true'
      block:
        - name: Include variables
          include_tasks: ./defaults/tasks/include_vars.yml
          
        - name: Install Ansible Tower
          include_tasks: ./defaults/tasks/install-towerfl.yml

- name: Configure Haproxy
  hosts: localhost
  connection: localhost
  gather_facts: false
  tasks:
    - name: Clean in-memory inventory
      meta: refresh_inventory

    - name: Setup haproxy pod
      include_tasks: ./defaults/tasks/setup-haproxy-pod.yml

