---
- name: Install single node tower for final lab
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Remove directory if it exists
      file:
        path: "{{ tower_setup_dir_path }}/ansible-tower-setup"
        state: absent
      tags:
        - install-tower

    - name: Download Tower Setup file
      unarchive:
        src: "https://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-{{ tower_version }}.tar.gz"
        dest: "{{ tower_setup_dir_path }}/"
        remote_src: true
      tags:
        - install-tower

    - name: Rename the ansible tower setup directory name
      shell: mv {{ tower_setup_dir_path }}/ansible-tower-setup-* {{ tower_setup_dir_path }}/ansible-tower-setup
      tags:
        - install-tower

    - name: Copy inventory file
      copy:
        src: inventory
        dest: "{{ tower_setup_dir_path }}/ansible-tower-setup/inventory"
      tags:
        - install-tower

    - name: Run Ansible Tower setup
      shell: ./setup.sh
      args:
        chdir: "{{ tower_setup_dir_path }}/ansible-tower-setup"
      async: 3600
      poll: 36
      tags:
        - install-tower
