---

- name: Set requirements file path
  set_fact:
    requirements_path: "{{ lab-manager }}/environments/{{ provisioner }}/{{ env_name }}/requirements.yml"

- name: Check if requirements.yml exists
  stat:
    path: "{{ requirements_path }}"
  register: r_requirements_stat

- set_fact:
    r_requirements_content: "{{ lookup('file', requirements_path) | from_yaml }}"
  when: r_requirements_stat.stat.exists

- name: Import collections from requirements.yml
  command: >-
    ansible-galaxy collection install
    -r "{{ requirements_path }}"
    -p "{{ lab_mgr_dir }}/collections"
    --force-with-deps
  when: >-
    r_requirements_stat.stat.exists
    and r_requirements_content | length > 0
    and r_requirements_content is mapping
    and "collections" in r_requirements_content
