version: 2
services:
  haproxy:
    build:
      context: .
      dockerfile: /opt/podman/resources/haproxypod/haproxy-Dockerfile         
    container_name: haproxy
    hostname: haproxy
    restart: always
    image: localhost/haproxy
    ports:
     - "8080:8080"
     - "8443:8443"
    volumes:
     - '/srv/haproxy/etc/haproxy:/etc/haproxy:Z'
     - '/srv/haproxy/etc/ssl/certs:/etc/ssl/certs:Z'
