- name: Setup Haproxy 
  hosts: localhost
  connection: localhost
  gather_facts: false
  tasks:
    - name: Include variables
      include_tasks: configs/include_vars.yml

    - set_fact:
        guid: "{{ access_details.guid }}"
        email: "{{ access_details.email }}"
        subdomain: "{{ access_details.subdomain }}"

    - name: Run haproxy pod
      include_tasks: configs/setup-haproxy-pod.yml
