---

- name: Locate config
  hosts: all:!controls:!bastions:!satellites
  gather_facts: false
  tasks:
    - name: Include environment variables
      include_tasks: ../tasks/lab-env-vars.yml  

    - name: Include networking
      include_tasks: ../tasks/lab-config-networking.yml
      when: default_networking | default(true) | bool

    - name: Include subscription
      include_tasks: ../tasks/lab-config-subscription.yml
      when: default_subscription | default(true) | bool


- name: Locate config
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Check if confige exists for the environment
      stat:
        path: "../../environments/{{ provisioner }}/{{ env_type }}/config.yml"
      register: stat_env_config


- name: Import config playbook from environment
  import_playbook:  "../../environments/{{ provisioner }}/{{ env_type }}/config.yml"
  when: hostvars.localhost.stat_env_config.stat.exists