---

- name: Locate config
  hosts: all:!controls:!bastions:!satellites
  connection: local
  gather_facts: false
  tasks:
    - name: Include environment variables
      include_tasks: ../tasks/lab-env-vars.yml  

    - name: Include environment variables
      include_tasks: ../tasks/lab-config-networking.yml

    - name: Include environment variables
      include_tasks: ../tasks/lab-config-subscription.yml


- name: Locate config
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Check if confige exists for the environment
      stat:
        path: "../../environments/{{ provisioner }}/{{ env_type }}/config.yml"
      register: stat_env_config

    - name: Use config from the environment
      set_fact:
        env_config_src: "../../environments/{{ provisioner }}/{{ env_type }}/config.yml"
      when: stat_env_config.stat.exists


- name: Import config playbook from environment
  import_playbook: "{{ hostvars['localhost']['env_config_src'] }}"
  when: hostvars.localhost.stat_env_config.stat.exists