---
- name: Include variables
  hosts: localhost
  connection: localhost
  gather_facts: false
  tasks:
    - name: Include environment variables
      include_tasks: ../tasks/lab-env-vars.yml

- name: Import destroy playbook from environment
  vars:
    find_destroy:
      - ../../environments/{{ provisioner }}/{{ env_type }}/destroy.yml
      - ./none.yml
  import_playbook: "{{ lookup('first_found', find_destroy) }}"


- name: Include variables
  hosts: localhost
  connection: localhost
  gather_facts: false
  tasks:
    - name: Destroy heat stack
      include_tasks: ../tasks/lab-env-destroy.yml

    - name: Saving inventory in /etc/ansible/hosts
      include_tasks: ../tasks/lab-ansible-inventory.yml

    # - name: update pod dns records
    #   include_tasks: ../tasks/lab-dns-records.yml
 

