---

- name: Include variables
  hosts: localhost
  connection: localhost
  gather_facts: false
  tasks:
    - name: Include environment variables
      include_tasks: ../defaults/tasks/lab-env-vars.yml
    
    - name: Provision lab environment
      include_tasks: ../defaults/tasks/lab-env-provisioner.yml

    - name: Saving inventory in /etc/ansible/hosts
      include_tasks: ../defaults/tasks/lab-ansible-inventory.yml

    - name: update pod dns records
      include_tasks: ../defaults/tasks/lab-dns-records.yml


- name: Wait for host to be available
  hosts: all:!controls:!bastions:!satellites
  gather_facts: false
  tasks:
    - when: "env_destroy | default(false) | bool != true"
      block:
        - name: wait for host to be available
          wait_for_connection:
            delay: 30
            timeout: 300
            connect_timeout: 10
          register: rwait
    
        - ping:
          register: rping
          retries: 3
          delay: 10
          until: rping is succeeded

