---

- name: Include variables
  hosts: localhost
  connection: localhost
  gather_facts: false
  tasks:
    - name: Include environment variables
      include_tasks: ../tasks/lab-env-vars.yml

    # Pod orchestration directory
    - name: Create podman orchestration directory
      file:
        path: "/opt/podman/pods/{{ item.name }}-pod/"
        state: directory
        owner: root
        group: root
        recurse: true
        mode: "u=rwx,g=rx,o=rx"
      loop: "{{ pods }}"

    # Pod volume directory
    - name: Create podman volume directories
      file:
        path: "/opt/podman/volumes/{{ item.0.name }}-volume/{{ item.1 }}"
        state: directory
        owner: root
        group: root
        recurse: true
        mode: "u=rwx,g=rx,o=rx"
      loop: "{{ pods|subelements('volumes') }}"

    # Pod dockerfile
    - name: Copy Dockerfile in orchestration dir
      copy:
        src: ../../environments/{{ provisioner }}/{{ env_type }}/{{ item.name }}/Dockerfile
        dest: "/opt/podman/pods/{{ item.name }}-pod/"
        owner: root
        group: root
        mode: "u=rwx,g=rx,o=rx"
      when: item.dockerfile | default(false) | bool
      loop: "{{ pods }}"

    # Pod compose file
    - name: Copy podman-compose file in orchestration dir
      copy:
        src: ../../environments/{{ provisioner }}/{{ env_type }}/{{ item.name }}/podman-compose.yml
        dest: "/opt/podman/pods/{{ item.name }}-pod/"
        owner: root
        group: root
        mode: "u=rwx,g=rx,o=rx"
      loop: "{{ pods }}"

    # Pod configuration templates 
    - name: Copy pods config templates
      template:
        src: ../../environments/{{ provisioner }}/{{ env_type }}/{{ item.0.name }}/{{ item.1.src }}
        dest: "/opt/podman/volumes/{{ item.0.name }}-volume/{{ item.1.dest }}"
        owner: root
        group: root
        mode: "u=rw,g=r,o=r"
      when: item.0.config_templates is defined
      loop: "{{ pods|subelements('config_templates', skip_missing=True) }}"

    # Pod configuration files
    - name: Copy pods config files
      copy:
        src: ../../environments/{{ provisioner }}/{{ env_type }}/{{ item.0.name }}/{{ item.1.src }}
        dest: "/opt/podman/volumes/{{ item.0.name }}-volume/{{ item.1.dest }}"
        owner: root
        group: root
        mode: "u=rw,g=r,o=r"
      when: item.0.config_files is defined
      loop: "{{ pods|subelements('config_files', skip_missing=True) }}"

    # Pod systemd service file
    - name: Copy podman systemd service config
      template:
        src: ../../environments/{{ provisioner }}/{{ env_type }}/{{ item.name }}/service.j2
        dest: "/usr/lib/systemd/system/{{ item.name }}-pod.service"
        owner: root
        group: root
        mode: "u=rw,g=r,o=r"
      loop: "{{ pods }}"

    ## Pod systemd service enable/start
    - name: Enable and Start pods
      service:
        name: "{{ item.name }}-pod"
        enabled: "{{ item.enabled | default(true) }}"
        state: "{{ item.state | default('started') }}"
      async: 3000
      poll: 30
      loop: "{{ pods }}"
