---
- name: configure and deploy pods
  hosts: localhost
  tasks:
    - name: Include variables
      include_tasks: configs/include_vars.yml

    - name: Run haproxy pod
      include_tasks: configs/setup-haproxy-pod.yml
      when: 'pod_type == "haproxy"'

    - name: Include tasks
      include_tasks: configs/setup-gitlab-pod.yml
      when: 'pod_type == "gitlab"'

