---

- name: Setup Haproxy 
  hosts: localhost
  become: true
  connection: localhost
  gather_facts: false
  tasks:
    - name: Clean in-memory inventory
      meta: refresh_inventory

    - name: Include environment variables
      include_tasks: ../tasks/lab-env-vars.yml  

    - set_fact:
        guid: "{{ access_details.guid }}"
        email: "{{ access_details.email }}"
        subdomain: "{{ access_details.subdomain }}"

    - name: copy haproxy.cfg
      template:
        src: ../templates/haproxy.cfg.j2
        dest: /opt/podman/volumes/haproxy-volume/etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: "u=rw,g=r,o=r"

    - name: Restart haproxy-pod
      service:
        name: haproxy-pod
        state: restarted
      async: 300
