---

- hosts: moleculenodes
  become: true
  gather_facts: false
  roles:
    - role: manager.common.common_vars
  tasks:
    - name: Configure motd
      copy:
        content: "Welcome to Molecule Lab"
        dest: /etc/motd

