################################################
#               SUMMARY
################################################
# Environment: Molecule
# No of Nodes: 1
# Nodes: node
# Image: rhel-8.3
# Type: GLOBAL-CPU_4_Memory_8192_Disk_30_flavor
# Network: dev
# Security Group: DefaultSG,WebSG,HostSG
###############################################

env_name: "{{ env_name }}"
guid: "{{ guid }}"
email: "{{ email }}"
project_tag: "{{ env_name }}-{{ guid }}"
provider_network: external
instance_network: default
all_ssh_authorized_keys: testkeys
default_metadata:
  owner: "{{ email | default('unknownuser') }}"
  Project: "{{ project_tag }}"
  guid: "{{ guid }}"
  env_name: "{{ env_name }}"

osp_default_rootfs_size: 50
# Default instance type
__instance_type: GLOBAL-CPU_4_Memory_8192_Disk_30_flavor 

# Default Image
__image: rhel-8.3
# Environment Instances
instances:
  - name: node
    count: "{{ node_instance_count | default(1) }}"
    public_dns: false
    dns_loadbalancer: false
    floating_ip: false
    image: "{{ node_instance_image | default(__image) }}"
    flavor:
      osp: "{{ node_instance_type | default(__instance_type) }}"
    network: "{{ instance_network | default('default') }}"
    tags:
      - key: "AnsibleGroup"
        value: "moleculenodes"
      - key: "ostype"
        value: "linux"
      - key: "instance_filter"
        value: "{{ env_name }}-{{ email }}"
      - key: "lab"
        value: "{{ instance_network }}"
      - key: "network"
        value: "{{ instance_network }}"
    security_groups:
      - DefaultSG
      - WebSG
      - HostSG

default_networking: false
