---
- name: "Create grader working directory {{ grader_working_dir }}"
  file:
    path:   "{{ grader_working_dir }}"
    state:  directory
    mode:   '0777'

- name: "Remove any existing grader report: {{ grader_student_report_file }}" 
  file:
    path: "{{ grader_student_report_file }}"
    state: absent
    
- name: "Generate header for new: {{ grader_student_report_file }}" 
  template:
    src:    grader_student_report_file.j2
    dest:   "{{ grader_working_dir }}/{{ grader_student_report_file }}"
    mode:   "0777"
...
