---

- name: Setup Haproxy 
  hosts: localhost
  become: true
  connection: localhost
  gather_facts: false
  roles:
    - role: manager.common.common_vars
  tasks:
    - name: copy haproxy.cfg
      template:
        src: haproxy.cfg.j2
        dest: "/opt/podman/volumes/haproxy-volume/etc/haproxy/haproxy.cfg"
        owner: root
        group: root
        mode: "u=rw,g=r,o=r"
      notify: restart_haproxy_pod

  handlers:
    - name: restart_haproxy_pod
      service:
        name: haproxy-pod
        state: restarted
      async: 300
