---

- name: Include variables
  hosts: localhost
  connection: localhost
  become: true
  tasks:
    - include_role:
        name: manager.common.letsecrypt

    - include_role:
        name: manager.local_pod.provisioner

    # Generate Letsencrypt certificate
    - name: Remove existing /tmp/cert.pem
      file:
        path: /tmp/haproxy.pem
        state: absent
      
    - name: merge private key and certificate
      shell: cat "{{ item }}" >> /tmp/haproxy.pem
      loop:
        - "/etc/letsencrypt/live/{{ groups['bastions'][0] | regex_replace('(\..*)?$', '') }}.{{ guid }}.{{ subdomain }}/privkey.pem"
        - "/etc/letsencrypt/live/{{ groups['bastions'][0] | regex_replace('(\..*)?$', '') }}.{{ guid }}.{{ subdomain }}/cert.pem"

    - name: copy merged certificate
      copy:
        src: /tmp/haproxy.pem
        dest: "/opt/podman/volumes/{{ env_name }}-volume/{{ ssl_cert_dirs }}/cert.pem"
        owner: root
        group: root
        mode: "u=rw,g=r,o=r"
     
    ## Pod systemd service enable/start
    - name: Enable and Start pods
      service:
        name: "{{ item.name }}-pod"
        state: restarted
      async: 3000
      poll: 30
      loop: "{{ pods }}"
