---

- name: Setup Haproxy 
  hosts: localhost
  become: true
  connection: localhost
  gather_facts: false
  tasks:
    - name: Clean in-memory inventory
      meta: refresh_inventory

    - name: Include environment variables
      include_tasks: "../../../defaults/tasks/lab-env-vars.yml"

    - name: copy haproxy.cfg
      template:
        src: haproxy.cfg.j2
        dest: "/opt/podman/volumes/haproxy-volume/etc/haproxy/haproxy.cfg"
        owner: root
        group: root
        mode: "u=rw,g=r,o=r"
      notify: restart_haproxy_pod

  handlers:
    - name: restart_haproxy_pod
      service:
        name: haproxy-pod
        state: restarted
      async: 300
