---

- name: update dns pod record
  hosts: localhost
  become: true
  connection: local
  gather_facts: False
  # roles:
  #   - role: manager.common.common_vars
  tasks:
    - name: Copy dns records
      template:
        src: example.com.zone.j2
        dest: "/opt/podman/volumes/bind9-volume/var/named/example.com.zone"
      notify: restart_dns_pod
  
  handlers:
    - name: restart_dns_pod
      service:
        name: "bind9-pod"
        state: restarted
