---
- name: Create Guid Keypair
  os_keypair:
    cloud: "{{ guid }}-project"
    state: present
    name: "{{ guid }}-keypair"
    public_key_file: "{{ user_public_key_file }}"

- name: Check Heat template
  include: ./defaults/tasks/lab-stack-check.yml

- name: Check if osp template exists for the environment
  stat:
    path: "./environments/{{ provisioner }}/{{ env_type }}/osp_template.j2"
  register: stat_osp_template

- name: Use osp template from the environment
  set_fact:
    osp_template_src: "./environments/{{ provisioner }}/{{ env_type }}/osp_template.j2"
  when: stat_osp_template.stat.exists

- name: Use the default infra template
  set_fact:
    osp_template_src: "./defaults/templates/osp_template.j2"
  when: not stat_osp_template.stat.exists

- name: Generate Heat Template
  template:
    src: "{{ osp_template_src }}"
    dest: /tmp/{{ env_type }}

- name: Create Heat stack from generated template
  command: >-
    openstack stack create -f json 
    --wait -t /tmp/{{ env_type }} 
    --os-cloud {{ guid }}-project
    {{ stack_name }}

- name: Grab outputs
  command: >-
    openstack stack show -f json 
    {{ stack_name }} 
    --os-cloud {{ guid }}-project
  register: heat_info

- name: show hot outputs
  debug:
    var: heat_info
    verbosity: 3

- name: set fact for hot_outputs
  set_fact:
    hot_outputs: "{{ (heat_info.stdout | from_json) }}"

- name: show hot_outputs
  debug:
    var: hot_outputs

