#################################
# Heat Stack Check tasks file
#################################

- name: exempted stack lists
  set_fact:
    exempted_stacks:
      - "base-stack-{{ guid }}"
    requested_stack: "{{ env_name }}-stack-{{ guid }}"
    filter_stack_list: []

- name: Add required stacks in exempted stack list
  set_fact:
    exempted_stacks: "{{ exempted_stacks + [ item + '-stack-' + guid ] }}"
  loop: "{{ stacks_required | default(['']) }}"

- name: Print exempted stacks
  debug:
    msg: "{{ exempted_stacks }}"
    verbosity: 2

- name: Gather existing stack list
  command: >-
    openstack stack list -c "Stack Name"  
    -f csv --os-cloud={{ guid }}-project
  register: __cloud_stacks

- name: filter stack_list
  set_fact:
     filter_stack_list: "{{ filter_stack_list | default([]) + [ item ] }}"
  when:
    - 'item != "Stack Name"'
    - 'item not in exempted_stacks'
  loop: "{{ __cloud_stacks.stdout_lines | regex_replace('\"','') }}"

- name: Print filter stacks
  debug:
    msg: "{{ filter_stack_list }}"
    verbosity: 2

- name: Stack doesn't exist
  assert:
    that:
      - 'requested_stack in filter_stack_list'
    fail_msg: "{{ env_name }}: environment doesn't exist"
