---

- name: Check osp stack
  include_role:
    name: manager.osp.osp_stack_checker

- name: Delete Heat stack from generated template
  command: >-
    openstack stack delete  
    --wait {{ env_name }}-stack-{{ guid }}
    --os-cloud {{ guid }}-project 

- pause:
    seconds: 10
