version: 2
services:
  haproxy:
         
    container_name: jenkins
    hostname: jenkins
    restart: always
    image: jenkins
    ports:
     - "8080:8080"
     - "8443:8443"
     - "8929:8929"
     - "1936:1936"
    volumes:
     - '/opt/podman/volumes/haproxy-volume/etc/haproxy:/etc/haproxy:Z'
     - '/opt/podman/volumes/haproxy-volume/etc/ssl/certs:/etc/ssl/certs:Z'