---

- name: Check if letsencrypt certificate exist
  stat:
    path: "/etc/letsencrypt/live/{{ groups['bastions'][0] | regex_replace('(\\..*)?$', '') }}.{{ guid }}.{{ subdomain }}"
  register: cert_stat
        
- name: Generate letsencrypt certificate
  when: not cert_stat.stat.exists | bool 
  command: >-
    certbot-3 certonly 
    --standalone 
    --email "{{ email }}"
    --agree-tos  
    -d "{{ groups['bastions'][0] | regex_replace('(\\..*)?$', '') }}.{{ guid }}.{{ subdomain }}" -n
