---

- name: Check if letsencrypt certificate exist
  stat:
    path: "/etc/letsencrypt/live/control.{{ guid }}.{{ subdomain }}"
  register: cert_stat
        
- name: Generate letsencrypt certificate
  when: not cert_stat.stat.exists | bool 
  command: >-
    certbot-3 certonly 
    --standalone 
    --email {{ email }}
    --agree-tos  
    -d control.{{ guid }}.{{ subdomain }} -n
