---

- name: Include variables
  hosts: localhost
  connection: localhost
  become: true
  tasks:
    - include_role:
        name: manager.common.letsecrypt

    - include_role:
        name: manager.local_pod.provisioner
      
    - name: Set host FQDN
      set_fact:
        letsencrypt_node: "{{ groups['bastions'][0] | regex_replace('(\\..*)?$', '') }}.{{ guid }}.{{ subdomain }}"

    - name: copy certificates
      copy:
        content: "/etc/letsencrypt/live/{{ letsencrypt_node }}/privkey.pem"
        dest: "/opt/podman/volumes/{{ env_name }}-volume/{{ ssl_cert_dirs }}/privkey.pem"
        owner: root
        group: root
        mode: "u=rw,g=r,o=r"

    - name: copy certificates
      copy:
        content: "/etc/letsencrypt/live/{{ letsencrypt_node }}/cert.pem"
        dest: "/opt/podman/volumes/{{ env_name }}-volume/{{ ssl_cert_dirs }}/cert.pem"
        owner: root
        group: root
        mode: "u=rw,g=r,o=r"

    ## Pod systemd service enable/start
    - name: Enable and Start pods
      service:
        name: "{{ item.name }}-pod"
        state: restarted
      async: 3000
      poll: 30
      loop: "{{ pods }}"
