---

- name: Include variables
  hosts: localhost
  connection: localhost
  become: true
  tasks:
    - include_role:
        name: manager.common.letsecrypt

    - include_role:
        name: manager.local_pod.provisioner
      
    - name: Set host FQDN
      set_fact:
        letsencrypt_node: "{{ groups['bastions'][0] | regex_replace('(\\..*)?$', '') }}.{{ guid }}.{{ subdomain }}"

    - name: copy private key in /tmp
      shell: (umask 022; cat /etc/letsencrypt/live/{{ letsencrypt_node }}/privkey.pem > /tmp/privkey.pem)

    - name: copy certificate in /tmp
      shell: (umask 022; cat /etc/letsencrypt/live/{{ letsencrypt_node }}/cert.pem > /tmp/cert.pem)

    - name: copy certificates
      copy:
        src: "/tmp/{{ item }}"
        dest: "/opt/podman/volumes/{{ env_name }}-volume/{{ ssl_cert_dirs }}/{{ item }}"
        owner: root
        group: root
        mode: "u=rw,g=r,o=r"
      loop:
        - privkey.pem
        - cert.pem



    ## Pod systemd service enable/start
    - name: Enable and Start pods
      service:
        name: "{{ item.name }}-pod"
        state: restarted
      async: 3000
      poll: 30
      loop: "{{ pods }}"
