- name: Download Tower Setup file
  unarchive:
    src: "https://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-{{tower_version}}.tar.gz"
    dest: /tmp/
    remote_src: yes 

- name: Remove directory if it exists
  file:
   path: /tmp/ansible-tower-setup-latest
   state: absent

- name: Rename the ansible tower setup directory name
  shell: mv /tmp/ansible-tower-setup-* /tmp/ansible-tower-setup-latest

- name: Run Ansible Tower setup
  shell: ./setup.sh -i /srv/lab-setup/files/towerfl-inventory
  args:
    chdir: /tmp/ansible-tower-setup-latest
  async: 3600
  poll: 36
