---

- become: true
  block:
          #    - name: DNS IP updated
          #      lineinfile:
          #        state: present
          #        path: /etc/sysconfig/network-scripts/ifcfg-eth0
          #        line: "{{ __network_conf }}"
          #      loop:
          #        - PEERDNS=no
          #        - DNS1={{ hostvars['control']['ansible_host'] }}
          #      loop_control:
          #        loop_var: __network_conf
          #      register: network_update
          #    
          #    - name: restart network manager
          #      service:
          #        name: NetworkManager
          #        state: restarted
          #      when: network_update.changed | bool
    
    - name: install katello-ca-consumer package
      yum:
        name: http://{{ satellite_url }}/pub/katello-ca-consumer-latest.noarch.rpm
        state: present
        disable_gpg_check: true
    
    - name: register system and attach subs
      redhat_subscription:
        state: present
        activationkey: "{{ satellite_activationkey }}"
        org_id: "{{ satellite_org }}"
    
    - name: Enable repositories
      rhsm_repository:
        name: "{{ item }}"
        state: enabled
      loop: "{{ rhel_repos }}"
