---

- name: Node setup
  hosts: satellites
  gather_facts: false
  become: true
  tasks:     
    - ping:

    - name: Refresh manifest
      command: >-
        /bin/hammer subscription refresh-manifest --organization=prod
      async: 300
      poll: 10

        