---

- name: Node setup
  hosts: satellites
  gather_facts: false
  become: true
  tasks:     
    - ping:

    - name: Refresh manifest
      shell: >-
        "sudo hammer subscription refresh-manifest --organization=prod"
      async: 300
      poll: 10

        