---
- name: Create Guid Keypair
  os_keypair:
    cloud: "{{ guid }}-project"
    state: present
    name: "{{ guid }}-keypair"
    public_key_file: "{{ user_public_key_file }}"

- name: Check Heat template
  include_tasks: check_stack.yml

- name: Check if osp template exists for the environment
  stat:
    path: "{{ lab_mgr_dir }}/environments/{{ provisioner }}/{{ env_name }}/osp_template.j2"
  register: stat_osp_template

- name: Use osp template from the environment
  set_fact:
    osp_template_src: "{{ lab_mgr_dir }}/environments/{{ provisioner }}/{{ env_name }}/{{ cloud_provider }}_template.j2"
  when: stat_osp_template.stat.exists

- name: Use the default infra template
  set_fact:
    osp_template_src: "osp_template.j2"
  when: not stat_osp_template.stat.exists

- name: Generate Heat Template
  template:
    src: "{{ osp_template_src }}"
    dest: /tmp/{{ env_name }}

- name: Create Heat stack from generated template
  command: >-
    openstack stack create -f json 
    --wait -t /tmp/{{ env_name }} 
    --os-cloud {{ guid }}-project
    {{ stack_name }}

- name: Grab outputs
  command: >-
    openstack stack show -f json 
    {{ stack_name }} 
    --os-cloud {{ guid }}-project
  register: heat_info

