---
- name: Install Grafana server
  hosts: metrics
  become: true
  tasks:
    - name: Include variables
      include_vars: vars.yml

    - name: Install grafana
      dnf:
        name: grafana
        state: installed

    - name: Start grafana
      service:
        name: grafana-server
        enabled: yes
        state: started